# Generated by Django 3.1.7 on 2021-02-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='img,null=True, blank=True', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
