# Generated by Django 3.1.7 on 2021-02-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20210228_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='img'),
        ),
    ]
